apiVersion: v1
kind: Pod
metadata:
  name: influxdb
  labels:
    app: influxdb
spec:
  containers:
  - name: influxdb 
    image: jasonwitting/alpine-influxdbv1:latest
    ports:
    - containerPort: 8083
      hostPort: 8083
    - containerPort: 8086
      hostPort: 8086
    
