- name: Make temp SSL Dir
  become: true
  file: path=/ssl/ state=directory mode=0777
  tags: 
    - common

- name: Copy kubernetes.pem to nodes
  become: true
  copy: src=../files/kubernetes.pem dest=/ssl/ mode=0644
  tags: 
    - common
  
- name: Copy kubernetes-key.pem to nodes
  become: true
  copy: src=../files/kubernetes-key.pem dest=/ssl/ mode=0644
  tags: 
    - common
  
- name: Copy ca.pem to nodes
  copy: src=../files/ca.pem dest=/ssl/ mode=0644
  become: true
  tags: 
    - common

- name: Install pip
  become: true
  apt: pkg=python-pip state=present
  tags: 
    - common  

- name: Install httplib2
  become: true
  pip: name=httplib2
  tags: 
    - common  
