- name: Create kubernetes dir
  become: true
  file: path=/var/lib/kubernetes state=directory
  when: ('controller' in group_names) or ('worker' in group_names)
  tags:
    - common
    
- name: "Install dependancies: pip, socat"
  become: true
  apt: 
    pkg:
      - python-pip
      - socat 
    state: present
  tags: 
    - common  

- name: Install httplib2
  become: true
  pip: name=httplib2
  tags: 
    - common  
