- name: Download kube-proxy binary
  become: true
  get_url: 
    url: https://storage.googleapis.com/kubernetes-release/release/v1.3.0/bin/linux/amd64/kube-proxy 
    dest: /usr/bin/kube-proxy
    mode: 0755
  tags:
    - kube-proxy

- name: Copy over kube-proxy service config
  become: true
  template: src=../files/kube-proxy.service.j2 dest=/etc/systemd/system/kube-proxy.service
  tags:
    - kube-proxy

- stat: path=/etc/systemd/system/kube-proxy.service
  register: kps
  tags:
    - kube-proxy

- name: Reload daemon
  become: true
  shell: "systemctl daemon-reload"
  when: kps.stat.exists == false
  tags:
    - kube-proxy 

- name: Enable kube-proxy service
  become: true
  shell: "systemctl enable kube-proxy"
  run_once: true
  tags:
    - kube-proxy

- name: Start kube-proxy
  become: true
  service: name=kube-proxy state=started
  tags:
    - kube-proxy

- name: Check Status
  become: true
  shell: "systemctl status kube-proxy --no-pager"
  register: kubeproxy_status
  ignore_errors: yes
  tags:
    - debug

- name: Cluster - kube controller status
  ignore_errors: yes
  debug: msg={{ kubeproxy_status.stdout_lines }}
  tags:
    - debug