- name: Create kubernetes dir
  become: true
  file: path=/var/lib/kubernetes state=directory
  tags:
    - kubectl

- name: Download kubectl binary
  become: true
  get_url: 
    url: https://storage.googleapis.com/kubernetes-release/release/v1.3.0/bin/linux/amd64/kubectl 
    dest: /usr/bin/kubectl
    mode: 0755
  tags:
    - kubectl

- name: Check if API server is installed
  stat: path=/etc/systemd/system/kube-apiserver.service
  register: apiserver

- name: Check Status
  become: true
  shell: "kubectl get componentstatuses"
  register: kubectl_status
  ignore_errors: yes
  when: apiserver.stat.exists == true
  tags:
    - debug

- name: Cluster - kube controller status
  debug: msg={{ kubectl_status.stdout_lines }}
  ignore_errors: yes
  when: apiserver.stat.exists == true
  tags:
    - debug