- name: Create kubernetes dir
  become: true
  file: path=/var/lib/kubernetes state=directory

- name: Copy SSL certs into dircetory   
  become: true
  shell: "cp /ssl/*.pem /var/lib/kubernetes/."

- name: Download kube-apiserver binary
  become: true
  get_url: 
    url: https://storage.googleapis.com/kubernetes-release/release/v1.3.0/bin/linux/amd64/kube-apiserver 
    dest: /usr/bin/kube-apiserver 
    mode: 0755

- name: Download auth token list
  become: true
  get_url: 
    url: https://raw.githubusercontent.com/kelseyhightower/kubernetes-the-hard-way/master/token.csv 
    dest: /var/lib/kubernetes/token.csv 
    mode: 0755

- name: Download auth policy 
  become: true
  get_url: 
    url: https://raw.githubusercontent.com/kelseyhightower/kubernetes-the-hard-way/master/authorization-policy.jsonl 
    dest: /var/lib/kubernetes/authorization-policy.jsonl
    mode: 0755

- name: Get internal ip
  uri: 
   url: http://metadata.google.internal/computeMetadata/v1/instance/network-interfaces/0/ip 
   HEADER_Metadata-Flavor: Google 
   method: GET
   return_content: yes
  register: internal_ip

- name: Copy over kube-apiserver.service
  become: true
  template: src=../files/kube-apiserver.service.j2 dest=/etc/systemd/system/kube-apiserver.service 
  notify: 
   - restart kube-apiserver

- stat: path=/etc/systemd/system/kube-apiserver.service
  register: ka

- name: Reload daemon
  become: true
  shell: "systemctl daemon-reload"
  when: ka.stat.exists == false 

- name: Enable kube-apiserver service
  become: true
  shell: "systemctl enable kube-apiserver"
  run_once: true  

- name: Start kube-apiserver
  become: true
  service: name=kube-apiserver state=started