- name: Copy kubernetes.pem to nodes
  become: true
  copy: src=../../../../ssl/kubernetes.pem dest=/var/lib/kubernetes/ mode=0644
  notify: 
    - restart kube-apiserver
    - restart kube-scheduler
    - restart kube-controller-manager
  tags: 
    - sslctrl
  
- name: Copy kubernetes-key.pem to nodes
  become: true
  copy: src=../../../../ssl/kubernetes-key.pem dest=/var/lib/kubernetes/ mode=0644
  notify: 
    - restart kube-apiserver
    - restart kube-scheduler
    - restart kube-controller-manager
  tags: 
    - sslctrl
  
- name: Copy ca.pem to nodes
  copy: src=../../../../ssl/ca.pem dest=/var/lib/kubernetes/ mode=0644
  become: true
  notify: 
    - restart kube-apiserver
    - restart kube-scheduler
    - restart kube-controller-manager
  tags: 
   - sslctrl

