
- name: Download docker binary
  become: true
  get_url: 
    url: https://get.docker.com/builds/Linux/x86_64/docker-1.11.2.tgz 
    dest: /tmp/docker-1.11.2.tgz
    mode: 0755
  tags:
    - docker

- stat: path=/tmp/docker/
  register: dd
  tags:
    - docker

- name: Untar docker-1.11.2.tgz
  become: true
  command: "tar xvfz /tmp/docker-1.11.2.tgz -C /tmp/" 
  when: dd.stat.exists == false
  tags:
    - docker

- stat: path=/usr/bin/docker
  register: dockerbin
  tags:
    - docker

- name: Copy docker binarys into /usr/bin
  become: true
  shell: "cp /tmp/docker/docker* /usr/bin/"
  when: dockerbin.stat.exists == false
  tags:
    - docker

- name: Copy over docker.service
  become: true
  template: src=../files/docker.service.j2 dest=/etc/systemd/system/docker.service 
  notify: 
    - restart docker.service
  tags:
    - docker

- stat: path=/etc/systemd/system/docker.service
  register: d
  tags:
    - docker

- name: Reload daemon
  become: true
  shell: "systemctl daemon-reload"
  when: d.stat.exists == false
  tags:
    - docker 

- name: Enable docker service
  become: true
  shell: "systemctl enable docker"
  tags:
    - docker

- name: Start docker
  become: true
  service: name=docker state=started
  tags:
    - docker

- name: Check Status
  become: true
  ignore_errors: yes
  shell: "systemctl status docker --no-pager"
  register: dockersrv_status
  tags:
    - debug

- name: Cluster - kube controller status
  ignore_errors: yes
  debug: msg={{ dockersrv_status.stdout_lines }}
  tags:
    - debug