- hosts: all
  remote_user: root
  roles:
    - { role: common, tags: common }            

- hosts: etcd
  remote_user: root
  roles:
    - { role: etcd, tags: etcd }

- hosts: controller
  remote_user: root
  roles:
    - { role: sslctrl, tags: sslctrl }
    - { role: kube-apiserver, tags: kube-apiserver }
    - { role: kube-controller, tags: kube-controller }
    - { role: kube-scheduler, tags: kube-scheduler }
    - { role: kubectl, tags: kubectl }
  
- hosts: worker
  remote_user: root
  roles:
    - { role: sslworker, tags: sslworker }
    - { role: cni, tags: cni }
    - { role: docker, tags: docker }
    - { role: kubectl, tags: kubectl }
    - { role: kube-proxy, tags: kube-proxy }
    - { role: kubelet, tags: kubelet }
   