- name: Download kube-scheduler binary
  become: true
  get_url: 
    url: https://storage.googleapis.com/kubernetes-release/release/v1.3.0/bin/linux/amd64/kube-scheduler 
    dest: /usr/bin/kube-scheduler 
    mode: 0755
  tags:
    - kube-scheduler

- name: Get internal ip
  uri: 
   url: http://metadata.google.internal/computeMetadata/v1/instance/network-interfaces/0/ip 
   HEADER_Metadata-Flavor: Google 
   method: GET
   return_content: yes
  register: internal_ip
  tags:
    - kube-scheduler

- name: Copy over kube-scheduler.service
  become: true
  template: src=../files/kube-scheduler.service.j2 dest=/etc/systemd/system/kube-scheduler.service 
  notify: 
   - restart kube-scheduler
  tags:
    - kube-scheduler 

- stat: path=/etc/systemd/system/kube-scheduler.service
  register: kss
  tags:
    - kube-scheduler

- name: Reload daemon
  become: true
  shell: "systemctl daemon-reload"
  when: kss.stat.exists == false
  tags:
    - kube-scheduler 

- name: Enable kube-scheduler service
  become: true
  shell: "systemctl enable kube-scheduler.service"
  run_once: true
  tags:
    - kube-scheduler

- name: Copy kubernetes.pem to nodes
  become: true
  copy: src=../../../../ssl/kubernetes.pem dest=/var/lib/kubernetes/ mode=0644
  notify: 
    - restart kube-scheduler
  tags: 
    - kube-scheduler
  
- name: Copy kubernetes-key.pem to nodes
  become: true
  copy: src=../../../../ssl/kubernetes-key.pem dest=/var/lib/kubernetes/ mode=0644
  notify: 
    - restart kube-scheduler
  tags: 
    - kube-scheduler
  
- name: Copy ca.pem to nodes
  copy: src=../../../../ssl/ca.pem dest=/var/lib/kubernetes/ mode=0644
  become: true
  notify: 
    - restart kube-scheduler
  tags: 
   - kube-scheduler


- name: Start kube-scheduler service
  become: true
  service: name=kube-scheduler state=started
  tags:
    - kube-scheduler

- name: Check Status
  become: true
  shell: "systemctl status kube-scheduler --no-pager"
  register: kubescheduler_status
  tags:
    - debug

- name: Cluster - kube controller status
  debug: msg={{ kubescheduler_status.stdout_lines }}
  tags:
    - debug